"""Update models relationships

Revision ID: 4fdd946c27d0
Revises: 327fe573ef1f
Create Date: 2025-01-19 19:57:29.027777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fdd946c27d0'
down_revision: Union[str, None] = '327fe573ef1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('operation', 'amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    op.drop_column('operation', 'created_at')
    # ### end Alembic commands ###
