"""add relation

Revision ID: aa14dc777b7a
Revises: 4fdd946c27d0
Create Date: 2025-01-19 20:02:44.711701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa14dc777b7a'
down_revision: Union[str, None] = '4fdd946c27d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet', 'balance',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet', 'balance',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
